### PR TITLE
Introduce breakpoint variables

### PR DESCRIPTION
**Pull request by jibiel**
MIrror breakpoint variables from [Semantic UI](https://github.com/Semantic-Org/Semantic-UI).

Tested on a simple page with grid. Looks like the PR does what it supposed to. Ideally should be tested on the existing app utilizing the gem if possible.

### CODE REVIEW

**Comment by doabit** [comment]
Great work, any possible to auto generate this codes after run `rake convert` to  update Semantic UI version?

**Comment by jibiel** [comment]
I'll look into it.

**Comment by jibiel** [comment]
@doabit Done. It's kinda hacky but it complies with the current rake task implementation.

One of the components is the exception though:

https://github.com/doabit/semantic-ui-sass/blob/498b8850ed8bc7436371bcb99e7be38d2e0cfe75/app/assets/stylesheets/semantic-ui/elements/_container.scss#L27-L28

https://github.com/doabit/semantic-ui-sass/blob/498b8850ed8bc7436371bcb99e7be38d2e0cfe75/app/assets/stylesheets/semantic-ui/elements/_container.scss#L45-L46

Container contains (duh) many indistinctable values which should be attended to semi-manually (similarly to the `$use-custom-scrollbars` case) which is simpler than to write complicated code which would basically contain almost the whole updated CSS anyway (only in Ruby).

**Comment by doabit** [comment]
Thanks.

**Pull request merged**
